### ISSUE TITLE
TwinDB agent init script on debian 8 is not compatible with systemd

### ISSUE THREAD

**Issue by ovaistariq** [twindb/twindb-agent#11]
Debian 8 uses systemd and expects to find the service definition at this path: /lib/systemd/system/
Should we setup setup systemd compatible service file on platforms?

Below is the error generated when trying to see if the twindb-agent service is enabled:
```
root@server55-default-debian-81:~# systemctl is-enabled twindb
Failed to get unit file state for twindb.service: No such file or directory
```

**Comment by akuzminsky** [comment]
```
vagrant@db01:~$ lsb_release -c
Codename:     jessie
vagrant@db01:~$ systemctl is-enabled twindb-agent
enabled
```
