### ISSUE TITLE
Agent fails to install on Debian wheezy

### ISSUE THREAD

**Issue by ovaistariq** [twindb/twindb-agent#15]
Reading package lists... Doneckage lists... 0%
Building dependency tree        
Reading state information... Done
Building data structures... Done 
Building data structures... Done 
Get:1 http://cloudfront.debian.net/debian/ wheezy/main lsof amd64 4.86+dfsg-1 [316 kB]
Get:2 https://packagecloud.io/twindb/main/debian/ wheezy/main mysql-connector-python all 2.0.4-1debian7.6 [111 kB]
Get:3 https://packagecloud.io/twindb/main/debian/ wheezy/main percona-xtrabackup amd64 2.2.12-1.wheezy [6252 kB]
Fetched 6679 kB in 0s (0 B/s)                                                   
           Selecting previously unselected package lsof.
           (Reading database ... 56960 files and directories currently installed.)
           Unpacking lsof (from .../lsof_4.86+dfsg-1_amd64.deb) ...
           Selecting previously unselected package mysql-connector-python.
           Unpacking mysql-connector-python (from .../mysql-connector-python_2.0.4-1debian7.6_all.deb) ...
           Selecting previously unselected package percona-xtrabackup.
           Unpacking percona-xtrabackup (from .../percona-xtrabackup_2.2.12-1.wheezy_amd64.deb) ...
           Processing triggers for man-db ...
           Setting up lsof (4.86+dfsg-1) ...
           Setting up mysql-connector-python (2.0.4-1debian7.6) ...
           Setting up percona-xtrabackup (2.2.12-1.wheezy) ...
Fetched 6679 kB in 0s (0 B/s)
           STDERR: dpkg-preconfigure: unable to re-open stdin: No such file or directory
           dpkg-preconfigure: unable to re-open stdin: No such file or directory
           /var/lib/dpkg/info/mysql-connector-python.postinst: 1: /var/lib/dpkg/info/mysql-connector-python.postinst: python2.6: not found
           dpkg: error processing mysql-connector-python (--configure):
            subprocess installed post-installation script returned error exit status 127
           Errors were encountered while processing:
        mysql-connector-python
       
       
           Error during install: 'installArchives() failed'

**Comment by ovaistariq** [comment]
Distributions shipping 2.6: https://packages.debian.org/search?keywords=python2.6&searchon=names&exact=1&suite=all&section=all
Distributions shipping 2.7: https://packages.debian.org/search?keywords=python2.7&searchon=names&exact=1&suite=all&section=all
So wheezy is listed in both 2.6 and 2.7 but this page says https://wiki.debian.org/Python:
Supported Python Versions:
Debian Wheezy contains Python 2.7 (default), 3.2

So there is a lot of contradiction.

**Comment by ovaistariq** [comment]
pyversions -s reports supported versions so wheezy still supports 2.6, that’s why its shown in the output. But that does not mean its installed as well.

**Comment by akuzminsky** [comment]
added dependency on python2.6 until https://bugs.mysql.com/bug.php?id=78425 is fixed
