### ISSUE TITLE
Packaging issues with Debian 7.8

### ISSUE THREAD

**Issue by ovaistariq** [twindb/twindb-agent#7]
running install_scripts
       creating /tmp/twindb-agent/build/twindb-agent-0.2.0/debian/twindb-agent/usr/bin
       copying build/scripts-2.7/twindb-agent -> /tmp/twindb-agent/build/twindb-agent-0.2.0/debian/twindb-agent/usr/bin
       changing mode of /tmp/twindb-agent/build/twindb-agent-0.2.0/debian/twindb-agent/usr/bin/twindb-agent to 755
       running install_egg_info
       Writing /tmp/twindb-agent/build/twindb-agent-0.2.0/debian/twindb-agent/usr/lib/python2.7/dist-packages/twindb_agent-0.2.0.egg-info
       /bin/sh: 3: python2.6: not found
       make[1]: *** [override_dh_install] Error 127
       make[1]: Leaving directory `/tmp/twindb-agent/build/twindb-agent-0.2.0'
       make: *** [binary] Error 2
       dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
       make[1]: Leaving directory `/tmp/twindb-agent'
       STDERR: /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'install_requires'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
         warnings.warn(msg)
       /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
         warnings.warn(msg)
       warning: sdist: standard file not found: should have one of README, README.txt
       
       warning: no previously-included files matching '__pycache__' found under directory '*'
       warning: no previously-included files matching '*.py[co]' found under directory '*'
       dch warning: Recognised distributions are: unstable, testing, stable,
       oldstable, experimental, {testing-,stable-,oldstable-,}proposed-updates,
       {testing,stable,oldstable}-security, wheezy-backports and UNRELEASED.
       Using your request anyway.
       debuild: fatal error at line 1357:
       dpkg-buildpackage -rfakeroot -D -us -uc failed
       make[1]: *** [build-deb] Error 29
       make: *** [package] Error 2

**Comment by akuzminsky** [comment]
This should be already fixed. Do you still see it?

**Comment by akuzminsky** [comment]
Deafult system python will be used for the agent
