### ISSUE TITLE
Missing package dependencies on Debian 8

### ISSUE THREAD

**Issue by ovaistariq** [twindb/twindb-agent#8]
Error during twindb-agent package installation:

Reading package lists... Doneckage lists... 0%
Building dependency tree        
Reading state information... Done
Building data structures... Done  17%
Building data structures... Done
           STDERR: This package is uninstallable
           Dependency is not satisfiable: mysql-connector-python (>= 2.0.0)

TwinDB repository not found:

W: Failed to fetch http://deb.twindb.com/dists/jessie/main/binary-amd64/Packages  404  Not Found
W: Failed to fetch http://deb.twindb.com/dists/jessie/main/binary-amd64/Packages  404  Not Found

**Comment by akuzminsky** [comment]
jessie is a new OS for TwinDB deb repo. So, yes, there are no packages in it.
Besides, we will have to package mysql-python-connector for Debian 8 because Orcale doesn't package it.

**Comment by akuzminsky** [comment]
I have to withdraw my previous comment.
There is no `mysql-connector-python` for Debian 8 on the [Download page](http://dev.mysql.com/downloads/connector/python/). But Oracle provides the APT repo for Debian 8 and we mirror `mysql-connector-python` and distribute it via our repo. Something must be wrong with our repo then.

**Comment by ovaistariq** [comment]
Do we have to start using the packagecloud based repository to avoid this bug? Can you upload all the other twindb packages as well, and then I can change my tests and the Chef deployment cookbook to then fetch the packages from packagecloud based repo.

**Comment by akuzminsky** [comment]
Yes, please use packagecloud. We will obsolete deb.twindb.com


On 1 September 2015 at 16:43, Ovais Tariq <notifications@github.com> wrote:

> Do we have to start using the packagecloud based repository to avoid this
> bug? Can you upload all the other twindb packages as well, and then I can
> change my tests and the Chef deployment cookbook to then fetch the packages
> from packagecloud based repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twindb/twindb-agent/issues/8#issuecomment-136893109>.
>



-- 
Aleksandr Kuzminsky
